### ISSUE TITLE
Not an issue but a question!

### ISSUE THREAD

**Issue by horst-n** [xurei/GIFDecoder_optimized#1]
Hi, many thanks for making this :)

I used the original classes from László Zsidi until I came across an issue with them or maybe this is already an issue with the way I implemented them, I'm not sure. However, after finding your class I get a part solved with it, but not all.

Problem is that images like this http://images.pw.nogajski.de/ANIMATEDGIF/animated-test-1.gif or this http://images.pw.nogajski.de/ANIMATEDGIF/animated-test-2.gif in my first implementation have positioned all frames at top 0 & left 0, what I could correct with reading the information from your new GIFGetFramesMeta() method :+1: - But I don't get them stuffed together after resizing without black areas or other artefacts. I'm not sure if and how I have to handle transparent index color or something like that. I want ask if you have some example code where I can see how to get rid of this? My current state looks like this: http://images.pw.nogajski.de/ANIMATEDGIF/animated-test-1-resized.gif - I also have had other results, without transparencies, but it looks like I'm far far away from understanding what has to be done here :)

**Comment by xurei** [comment]
I had the same issue after pushing this class, but never sent the fix, sorry about that.
If you are using the GIFEncoder from László, try the one I just pushed in this repository. This piece of code should do the work :

``` php
$gif = new GIFEncoder(
    $frames,
    $meta['delays'],
    $meta['loops'],
    $meta['disposal'],
    $meta['r'],$meta['g'],$meta['b'],
    "url"); 

$content = $gif->GetAnimation();
```

If you want to learn more about how GIFs are encoded, I suggest you read this : http://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp
That was a precious resource to enhance GIFEncoder and GIFDecoder.

Hope this helps !

**Comment by horst-n** [comment]
Hey, very kind!

Yes it helped a lot. I need to do it step by step, (in very little steps :) ), but now I got a first version running: http://images.pw.nogajski.de/ANIMATEDGIF/animated-test-1-resize-success.gif 
https://github.com/horst-n/ImageAnimatedGif/tree/dev

Many thanks!
