### ISSUE TITLE
Question to the licences of the libraries

### ISSUE THREAD

**Issue by horst-n** [xurei/GIFDecoder_optimized#2]
Hi Olivier,

we want to include both libraries, gif-encoder and gif-decoder, into an open source project. (https://github.com/processwire). But there are nowhere stated which licences are bundled with the libraries. On phpclasses.org, there is stated "Freeware", what seems to be no licence at all. Are you able to bundle, for example a MIT or LGPL licence with the libs? Or is László Zsidi the only person who can do this?
( I tried already to contact him, but only have the support-thread-forum at phpclasses.org, where he seems to be last active two years ago: https://www.phpclasses.org/discuss/package/3163/thread/63/ )

Best regards,
Horst

**Comment by xurei** [comment]
Hello Horst,

Glad to hear you like my work :-)

As I only improved the codebase from PHPClasses, I don't own the intellectual property to license it - except my changes, which you can consider under MIT license (as long as it is not conflicting with the original one).

You will need to call László Zsidi to get the license/authorization for the whole package. 

I didn't go to PHPClasses for a while. I have no idea how they deal with licenses, sorry...

Hope it helps anyway :-)

**Comment by horst-n** [comment]
Hi @xurei,
I want ask if you can follow Laszlo and add the Apache 2.0 or a compatible licence to both GIF libraries?
https://github.com/jacoka/GIFDecoder/issues/1#issuecomment-353263850
Laszlo was so kind and created a repo here on Github and added the Apache licence to both libraries. 
Once again, many thanks for your improvements and your time. 😀

**Comment by xurei** [comment]
Done
